name: Semantic PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  semantic:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Reads config from .github/semantic.yml
          validateSingleCommit: false

