#/!/usr/bin/env just

# Setup your project for development during Crowdbotics conversion to Xperts
init-from-crowdbotics:
    #!/usr/bin/env bash

    # todo: copy .xperts/dev-helpers/ios.json to ios.json
    # todo: copy .xperts/dev-helpers/android.json to android.json
    # todo: copy .xperts/dev-helpers/custom-actions/ to custom-actions/

    # todo: ensure package.json exists; create if not
    # todo: ensure package.json contains a version key; add if not -> set to "2.0.0"
