name: 'Android Build'
description: Build Android app bundle and upload artifacts

inputs:
  env:
    description: "App environment: 'staging' or 'production'"
    required: false
    default: 'staging'
  aab-path:
    description: 'Path to generated AAB file'
    required: false
    default: 'android/app/build/outputs/bundle/release/app-release.aab'
  manifests-path:
    description: 'Path to merged manifests dir'
    required: false
    default: 'android/app/build/intermediates/merged_manifests'
  debug-symbols-path:
    description: 'Path to debug symbols dir'
    required: false
    default: 'android/app/build/intermediates/merged_native_libs/release/out/lib'
  app-artifact-name:
    description: 'Name for the Android app artifact'
    required: false
    default: 'Android'
  manifests-artifact-name:
    description: 'Name for the merged manifests artifact'
    required: false
    default: 'MergedManifests'
  debug-symbols-artifact-name:
    description: 'Name for the debug symbols artifact'
    required: false
    default: 'DebugSymbols'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: 'Setup Android SDK'
      uses: android-actions/setup-android@v2

    - name: 'Install Node.js'
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: 'Enable Corepack'
      shell: bash
      run: corepack enable

    - name: 'Configure App Environment'
      shell: bash
      env:
        ENV: ${{ inputs.env == 'production' && 'production' || 'staging' }}
      run: |
        printf "// THIS FILE IS AUTO GENERATED. DO NOT MANUALLY MODIFY.\nconst env = '%s';\nexport default env;\n" "$ENV" > env.js

    - name: 'Run Build Script'
      shell: bash
      run: |
        sh ./scripts/build-android.sh

    - name: 'Upload Merged Manifest Artifacts'
      uses: actions/upload-artifact@v4
      with:
        name: 'android-merged-manifests'
        path: ${{ inputs.manifests-path }}

    - name: 'Upload Debug Symbols Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: 'android-debug-symbols'
        path: ${{ inputs.debug-symbols-path }}

    - name: 'Upload Android App Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: 'android'
        path: ${{ inputs.aab-path }}
