name: 'Build Python Docker Images'

on:
  workflow_dispatch:
    inputs:
      push_images:
        description: 'Push images to registry'
        type: boolean
        default: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: xperts-python-slim

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        python_version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Login to Container Registry'
        if: ${{ github.event.inputs.push_images == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Extract metadata'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.python_version }}

      - name: 'Build and push Docker image'
        uses: docker/build-push-action@v5
        with:
          context: images/xperts-python-slim
          file: images/xperts-python-slim/Dockerfile
          push: ${{ github.event.inputs.push_images == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PY_VER=${{ matrix.python_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
